In [2]:
import numpy as np

как создать матрицу?

In [3]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [4]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# размер матрицы
np.shape(A)

(4, 3)

In [6]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [7]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [8]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [9]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


создание специальных матриц

In [10]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [15]:
A = np.array([[1,1],[2,3],[4,5]])
B = np.array([[1,-1],[-2,3],[4,-5]])
print('matrix A:\n', A)
print('matrix B:\n', B)

#операции с матрицами
print('matrix sum_1:\n', A+B)
print('matrix sum_2:\n', B+A)
print('matrix diff:\n', A-B)
print('matrix prod:\n', 2*A)
print('matrix A transp:\n', A.T)

matrix A:
 [[1 1]
 [2 3]
 [4 5]]
matrix B:
 [[ 1 -1]
 [-2  3]
 [ 4 -5]]
matrix sum_1:
 [[2 0]
 [0 6]
 [8 0]]
matrix sum_2:
 [[2 0]
 [0 6]
 [8 0]]
matrix diff:
 [[ 0  2]
 [ 4  0]
 [ 0 10]]
matrix prod:
 [[ 2  2]
 [ 4  6]
 [ 8 10]]
matrix A transp:
 [[1 2 4]
 [1 3 5]]


In [16]:
# как транспонировать вектор?
x = np.array([1,2,3])
x.T

array([1, 2, 3])

In [17]:
x_col = np.reshape(x, (3,1))
print(x_col)
print(np.shape(x_col))
x_col.T

[[1]
 [2]
 [3]]
(3, 1)


array([[1, 2, 3]])

In [18]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


Умножение матриц

In [26]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

print('матрица A:\n', A)
print('матрица B:\n', B)

# Поэлементное умножение
print('поэлементное умножение:\n', A*B)

матрица A:
 [[11  9 11]
 [11  8 11]
 [ 6  5  6]]
матрица B:
 [[ 2 -2  1]
 [ 3 -1 -1]
 [ 0  2  1]]
поэлементное умножение:
 [[ 22 -18  11]
 [ 33  -8 -11]
 [  0  10   6]]


In [27]:
# тип np.matrix
A_m = np.matrix(A)
B_m = np.matrix(B)
print(A_m*B_m)

[[49 -9 13]
 [46 -8 14]
 [27 -5  7]]


In [28]:
# Матричное умножение
np.dot(A,B)

array([[49, -9, 13],
       [46, -8, 14],
       [27, -5,  7]])

In [29]:
# Матричное умножение
A@B

array([[49, -9, 13],
       [46, -8, 14],
       [27, -5,  7]])

In [30]:
# Порядок умножения AB != BA
B@A

array([[ 6,  7,  6],
       [16, 14, 16],
       [28, 21, 28]])

In [31]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 6 11  5  8 11]
 [ 7 11 10  8  6]
 [ 9  9 11  9  6]]
B:
 [[ 3 -2]
 [ 0  2]
 [-1  3]
 [-2  2]
 [ 0  2]]


In [32]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[-3, 63],
       [-5, 66],
       [-2, 63]])

In [33]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [34]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [35]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-3 -4 -2  3]
 [-3 -4 -2 -1]
 [ 1 -3 -3  0]
 [ 0  0 -4  0]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-3 -8  0 -3]
 [-3 -8  0  1]
 [ 1 -6  0  0]
 [ 0  0  0  0]]
DA:
 [[-3 -4 -2  3]
 [-6 -8 -4 -2]
 [ 0  0  0  0]
 [ 0  0  4  0]]


In [38]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
print('Ab:\n', A@b)

Ab:
 [2 6]


In [37]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [39]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[2, 2],
       [2, 3]])

In [40]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [41]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [42]:
# ортонормированные системы
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])