In [1]:
import numpy as np

# Создание матриц

In [2]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [3]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# размер матрицы
np.shape(A)

(4, 3)

In [5]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [6]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [7]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [8]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


# Cоздание специальных матриц

In [9]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [14]:
A = np.array([[1,1],[2,3],[4,5]])
B = np.array([[1,-1],[-2,3],[4,-5]])
print('matrix A:\n', A)
print('matrix B:\n', B)

#операции с матрицами
print('matrix sum_1:\n', A+B)
print('matrix sum_2:\n', B+A)
print('matrix diff:\n', A-B)
print('matrix prod:\n', 2*A)
print('matrix A transp:\n', A.T)

matrix A:
 [[1 1]
 [2 3]
 [4 5]]
matrix B:
 [[ 1 -1]
 [-2  3]
 [ 4 -5]]
matrix sum_1:
 [[2 0]
 [0 6]
 [8 0]]
matrix sum_2:
 [[2 0]
 [0 6]
 [8 0]]
matrix diff:
 [[ 0  2]
 [ 4  0]
 [ 0 10]]
matrix prod:
 [[ 2  2]
 [ 4  6]
 [ 8 10]]
matrix A transp:
 [[1 2 4]
 [1 3 5]]


In [15]:
# как транспонировать вектор?
x = np.array([1,2,3])
x.T

array([1, 2, 3])

In [16]:
x_col = np.reshape(x, (3,1))
print(x_col)
print(np.shape(x_col))
x_col.T

[[1]
 [2]
 [3]]
(3, 1)


array([[1, 2, 3]])

In [17]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


# Умножение матриц

In [18]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

print('матрица A:\n', A)
print('матрица B:\n', B)

# Поэлементное умножение
print('поэлементное умножение:\n', A*B)

матрица A:
 [[10  8 11]
 [10  5  6]
 [ 8 10  9]]
матрица B:
 [[-1  0  0]
 [ 2  3  0]
 [-1 -2 -2]]
поэлементное умножение:
 [[-10   0   0]
 [ 20  15   0]
 [ -8 -20 -18]]


In [19]:
# тип np.matrix
A_m = np.matrix(A)
B_m = np.matrix(B)
print(A_m*B_m)

[[ -5   2 -22]
 [ -6   3 -12]
 [  3  12 -18]]


In [20]:
# Матричное умножение
np.dot(A,B)

array([[ -5,   2, -22],
       [ -6,   3, -12],
       [  3,  12, -18]])

In [21]:
# Матричное умножение
A@B

array([[ -5,   2, -22],
       [ -6,   3, -12],
       [  3,  12, -18]])

In [22]:
# Порядок умножения AB != BA
B@A

array([[-10,  -8, -11],
       [ 50,  31,  40],
       [-46, -38, -41]])

In [23]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[10  5  8  8  9]
 [11 10  8  9  6]
 [11 11 10  6  9]]
B:
 [[ 1  0]
 [ 2 -1]
 [-1  3]
 [-1  2]
 [ 1 -1]]


In [24]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[13, 26],
       [20, 26],
       [26, 22]])

In [25]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [26]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [27]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 2  2  1 -4]
 [ 3 -2 -1 -2]
 [-4 -2  3  1]
 [-4  1 -1  1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 2  4  0  4]
 [ 3 -4  0  2]
 [-4 -4  0 -1]
 [-4  2  0 -1]]
DA:
 [[ 2  2  1 -4]
 [ 6 -4 -2 -4]
 [ 0  0  0  0]
 [ 4 -1  1 -1]]


In [28]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
print('Ab:\n', A@b)

Ab:
 [2 6]


In [29]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [30]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [31]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [32]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [33]:
# ортонормированные системы
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

# Обратная матрица

In [34]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [35]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [36]:
# вычисление определителя
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))

-2.9999999999999996


# Обратная матрица, определитель, ранг

In [38]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

# Мы видим, что ранг системы равен 2, а векторов три — значит система является линейно зависимой. 

2


In [39]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

# В данном примере ранг равен 3 — значит векторы линейно независимы.

3


In [26]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [27]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [28]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)

A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [29]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]] 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
check OK


In [30]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [31]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [32]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

LinAlgError: Singular matrix

In [33]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

rk(A3):
 2


In [35]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

LinAlgError: Singular matrix

In [36]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

LinAlgError: Singular matrix

In [37]:
print('det(A1)):\n',np.linalg.det(A1))

det(A1)):
 -2.9999999999999996


In [38]:
print('det(A2)):\n',np.linalg.det(A2))

det(A2)):
 0.0


In [39]:
print('det(A3)):\n',np.linalg.det(A3))

det(A3)):
 0.0


In [40]:
# обратная матрица - неустойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

A4:
 [[1.      2.      3.     ]
 [4.      5.      6.     ]
 [1.      2.      3.00005]]
rk(A4):
 3
det(A4):
 -0.00014999999999965044
A4 inverse:
 [[-2.00016667e+04  6.66666667e-01  2.00000000e+04]
 [ 4.00013333e+04 -3.33333333e-01 -4.00000000e+04]
 [-2.00000000e+04  0.00000000e+00  2.00000000e+04]]


In [41]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

A5:
 [[1.         2.         3.        ]
 [4.         5.         6.        ]
 [1.         2.         3.00000005]]
rk(A5):
 3
det(A5):
 -1.5000000042064706e-07
A5 inverse:
 [[-2.00000016e+07  6.66666667e-01  1.99999999e+07]
 [ 4.00000012e+07 -3.33333333e-01 -3.99999999e+07]
 [-1.99999999e+07  0.00000000e+00  1.99999999e+07]]


In [42]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

A:
 [[1 1]
 [2 1]
 [1 1]]
Матрица Грама:
 [[6 4]
 [4 3]]


In [43]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

Ранг матрицы Грама:
 2


In [44]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

Определитель матрицы Грама:
 2.0000000000000004


In [45]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))

Обратная к матрице Грама:
 [[ 1.5 -2. ]
 [-2.   3. ]]
