In [15]:
import pandas as pd
import numpy as np

In [2]:
# Данные по доходам и расходам каждого члена семьи
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [3]:
# матрица с доходами
inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
print(inc)

[[100 150  90]
 [220 200  80]
 [140 130 100]]


In [4]:
# матрица с расходами
cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
print(cons)

[[ 50 100 100]
 [ 50  80  20]
 [ 60 140 140]]


In [5]:
# матрица с доходами после вычета налогов
after_tx = inc*0.87
print(after_tx)

[[ 87.  130.5  78.3]
 [191.4 174.   69.6]
 [121.8 113.1  87. ]]


In [11]:
# матрица с балансом
P = after_tx-cons
print(P)

[[ 37.   30.5 -21.7]
 [141.4  94.   49.6]
 [ 61.8 -26.9 -53. ]]


# Задача 2

In [8]:
# Даны матрица  и вектор х
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

# произведение матрицы и ветора
print(A@x)

[26 30]


In [9]:
# Даны две матрицы
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

# произведение матриц
print(B@A)

[[  2   9  11  14]
 [  8 -10 -14 -11]]


In [13]:
# Дана система векторов
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

# матрица их векторов
A = np.array([x, y, z])

# матрица Грама
G = A.T@A
print(G)

[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


В салоне красоты работают восемь стилистов. Есть две таблицы (DataFrame): Count_DF и Price_DF.
В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [19]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

# Вектор комиссий:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [24]:
Count_DF_values = Count_DF.values
print('количество услуг:\n', Count_DF_values)

количество услуг:
 [[10  5 12 15 10]
 [ 2 21  3 25  6]
 [12 12  0 30  4]
 [ 4  8 18 14  5]
 [ 6 25 27 25 18]
 [10  3  2 17 12]
 [22  1  4 25 20]
 [ 7  0 31 31 28]]


In [25]:
Price_DF_values = Price_DF.values
print('стоимость услуг:\n', Price_DF_values)

стоимость услуг:
 [[2.  1.5 1.  0.8 1. ]
 [1.8 2.5 1.  1.  1. ]
 [2.  2.  0.  0.5 2. ]
 [1.8 1.2 2.8 0.8 2. ]
 [2.5 3.5 2.  1.  1.5]
 [5.  5.  3.  2.  2.5]
 [1.1 1.  1.5 0.5 1.7]
 [4.5 4.  2.5 1.  2. ]]


In [26]:
Amount_DF = Count_DF_values*Price_DF_values
print('доход от услуг:\n', Amount_DF)

доход от услуг:
 [[20.   7.5 12.  12.  10. ]
 [ 3.6 52.5  3.  25.   6. ]
 [24.  24.   0.  15.   8. ]
 [ 7.2  9.6 50.4 11.2 10. ]
 [15.  87.5 54.  25.  27. ]
 [50.  15.   6.  34.  30. ]
 [24.2  1.   6.  12.5 34. ]
 [31.5  0.  77.5 31.  56. ]]


In [29]:
Amount_com_DF = Amount_DF@com
print('доход салона:\n', Amount_com_DF)

доход салона:
 [11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [36]:
mast = np.ones((1,5))-com
Amount_mast_DF = Amount_DF@mast.T
print('доход мастеров:\n', Amount_mast_DF)

доход мастеров:
 [[ 50.2 ]
 [ 74.88]
 [ 59.1 ]
 [ 67.8 ]
 [166.6 ]
 [113.8 ]
 [ 66.21]
 [157.75]]
