In [11]:
import pandas as pd
import numpy as np

# Задача 1

фрагмент базы данных агентства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [4]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

Hut_Paradise_DF

,1.Rent,2.Area,3.Rooms,4.Floor,5.Demo two weeks,6.Liv.Area
0,65,50,3,5,8,37
1,70,52,2,12,4,40
2,120,80,1,10,5,65
3,35,33,1,3,10,20
4,40,33,1,6,20,16
5,50,44,2,13,12,35
6,100,80,4,8,5,60
7,90,65,3,21,1,50
8,85,65,2,5,10,40


In [6]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

параметры квартиры номер 5

In [7]:
print('Fifth apartment vector:\n', Hut_Paradise_values[4]) # пятая строка матрицы

Fifth apartment vector:
 [40 33  1  6 20 16]


этажи всех квартир

In [9]:
print('Floor vector:\n', Hut_Paradise_values[:,3]) # третий столбец матрицы

Floor vector:
 [ 5 12 10  3  6 13  8 21  5]


нежилая прощадь квартир

In [10]:
print('non_liv.area:', Hut_Paradise_values[:,1]-Hut_Paradise_values[:,5])

non_liv.area: [13 12 15 13 17  9 20 15 25]


продолжительность просмотров в минутах во всех квартирах за две недели

In [13]:
demo_time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

all_time = np.dot(Hut_Paradise_values[:,4], demo_time)
print('total_demo_time:', all_time)

total_demo_time: 1348


# Задача 2

In [14]:
# дано три вектора
u = np.array([3,0,1,1,1])
v = np.array([0,1,0,2,-2])
w = np.array([1,-4,-1,0,-2])

In [15]:
# линейная комбинация векторов v и w с коэффициентами 2 и -3
d=2*v+-3*w
print('linear combination:', d)

linear combination: [-3 14  3  4  2]


In [16]:
# ортогональность линейной комбинации и вектора u
print('ортогональность:',np.dot(u,d))

ортогональность: 0
