In [1]:
import numpy as np

In [2]:
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [3]:
s[2]

50

In [4]:
len(s)

4

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [6]:
a + b

array([15, 23, 14,  8])

In [7]:
a - b

array([ 5, -7, -4, -6])

In [8]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])